<head>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
</head>

<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<?php $collection = $this->getCollection();?>

<!--<form id="testimonials-form" method="post" action="index/submitTestimonials">
-->
<form id="testimonials-form" method="post" action="" enctype="multipart/form-data">

<div class="top-page-container">
<h1>Testimonials</h1>
    <?php if (Mage::getSingleton('customer/session')->isLoggedIn()): ?>
        <button id="submit-btn" type="submit" name="submit-testimonial" onclick="doAjax()">SUBMIT YOUR TESTIMONIAL</button>
        <textarea id="textareaTestimonial" name="textareaTestimonialName" placeholder="Enter your feedback here..."></textarea>
        <?php else: ?>
        <div id="login-text">To leave a feedback you need to log in</div>
        <?php endif ?>
        </div>
</form>

<?php if($collection->getSize()): ?>
    <div style="padding-top: 0px; margin: 0 auto">
    <?php foreach ($collection as $item): ?>
        <?php if($item->getIsActive()): ?>
            <div class="hero">
                <?php echo $item->getContent(); ?>
                <?php echo ' (' .$item->getCreatedDate() . ')'; ?>
            </div>
            <div id="customers-name">
                <?php $customer = Mage::getModel('customer/customer')->load($item->getCustomerId()); ?>
                <?php echo  $customer->getName(); ?>
            </div>
        <?php endif ?>
    <?php endforeach; ?>
    </div>
    <div class="pagination">
    <?php echo $this->getPagerHtml(); ?>
    </div>
<?php else: ?>
    <br><p><?php echo $this->__('No testimonials were added. Log in to be the first...'); ?>
    </p>
<?php endif ?>


<script type="text/javascript">

/*
        $("#submit-btn").click(function () {
            doAjax();
            //$("#textareaTestimonial").css("border","5px solid red");
            //$("#textareaTestimonial").text("Lol, enter something").css("color", "blue");
        })(jQuery);
*/
        function doAjax() {
            console.log('test');
            //$.ajax({
            jQuery.ajax({
                url: "<?php echo Mage::getBaseUrl() . 'blog/index/submitTestimonials' ?>",
                type: "POST",
                //data: $("#textareaTestimonial"),
                //data : $("#testimonials-form").serializeArray(),
                dataType: 'json',
                success: function () {
                    console.log('test2');
                    jQuery("#textareaTestimonial").css("border", "3px solid green");
                },
                error: function () {
                    console.log('test3');
                    jQuery("#textareaTestimonial").css("border", "3px solid red");
                }
            });
        }
</script>
<script>jQuery.noConflict();</script>