<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<?php $collection = $this->getCollection();?>

<form id="testimonials-form" action="<?php echo Mage::getBaseUrl() . 'blog/index/submitTestimonials' ?>" method="post">

<div class="top-page-container">
<h1>Testimonials</h1>
    <?php if (Mage::getSingleton('customer/session')->isLoggedIn()): ?>
        <button id="submit-btn" type="submit" name="submit-testimonial" onclick="testimonialsForm.submit(this); return false;">SUBMIT YOUR TESTIMONIAL</button>
        <textarea id="textareaTestimonial" class="input-text required-entry" name="textareaTestimonialName" placeholder="Enter your feedback here..."></textarea>
        <?php else: ?>
        <div id="login-text">To leave a feedback you need to log in</div>
        <?php endif ?>
        </div>
</form>

<?php if($collection->getSize()): ?>
    <div style="padding-top: 0px; margin: 0 auto">
    <?php foreach ($collection as $item): ?>
        <?php if($item->getIsActive()): ?>
            <div class="hero">
                <?php echo $item->getContent(); ?>
                <?php echo ' (' .$item->getCreatedDate() . ')'; ?>
            </div>
            <div id="customers-name">
                <?php $customer = Mage::getModel('customer/customer')->load($item->getCustomerId()); ?>
                <?php echo  $customer->getName(); ?>
            </div>
        <?php endif ?>
    <?php endforeach; ?>
    </div>
    <div class="pagination">
    <?php echo $this->getPagerHtml(); ?>
    </div>
<?php else: ?>
    <br><p><?php echo $this->__('No testimonials were added. Log in to be the first...'); ?>
    </p>
<?php endif ?>

<script type="text/javascript">
    //<![CDATA[
    var testimonialsForm = new VarienForm('testimonials-form', true);
    testimonialsForm.submit = function(button, url) {
        if (this.validator.validate()) {
            var data = jQuery('#testimonials-form').serialize();
            jQuery.ajax({
                url: this.form.action,
                type: "POST",
                data: data,
                dataType: 'text',
                success: function (msg) {
                    jQuery("#textareaTestimonial").css("border", "2px solid #1ebd9d");
                    alert(msg);
                    jQuery("#textareaTestimonial").css("border", "1px solid silver");
                    jQuery("#textareaTestimonial").val('');
                },
                error: function () {
                    jQuery("#textareaTestimonial").css("border", "3px solid red");
                }
            });

            return false;
        }
    }.bind(testimonialsForm);
    //]]>
</script>